# build and test golang services

name: build-and-test

on: [push]
jobs:
  build:
    runs-on: ubuntu-16.04
    name: golang-build-test
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '^1.14.10'
      - run: go version
      - run: ls
      - run: sh scripts/external-sh-hello.sh




